name: CI

on:
  pull_request:
    branches: develop
    types: [opened, synchronize, reopened, closed]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  frontend:
    if: ${{ github.event.action != 'closed' || github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          check-latest: true
      - name: Install dependencies
        working-directory: ./src/frontend
        run: npm ci
      - name: Check Format
        working-directory: ./src/frontend
        run: npm run format:check
      - name: Lint
        working-directory: ./src/frontend
        run: npm run lint
      - name: Build
        working-directory: ./src/frontend
        run: npm run build -- --no-lint
      - name: Test
        working-directory: ./src/frontend
        run: npm run test

  server:
    if: ${{ github.event.action != 'closed' || github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          check-latest: true
      - name: Install dependencies
        working-directory: ./src/server
        run: npm ci
      - name: Check Format
        working-directory: ./src/server
        run: npm run format:check
      - name: Build
        working-directory: ./src/server
        run: npm run build
      - name: Start
        working-directory: ./src/server
        run: |
          npm start &
          sleep 2
          kill $!
      - name: Test
        working-directory: ./src/server
        run: npm run test
