name: CI

on:
  pull_request:
    branches: develop
    types: [opened, synchronize, reopened, closed]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      server: ${{ steps.filter.outputs.server }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check for file changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'src/frontend/**'
            server:
              - 'src/server/**'

  frontend:
    needs: changes
    if: ${{ (github.event.action != 'closed' || github.event.pull_request.merged) && needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          check-latest: true
      - name: Install dependencies
        working-directory: ./src/frontend
        run: npm ci
      - name: Check Format
        working-directory: ./src/frontend
        run: npm run format:check
      - name: Lint
        working-directory: ./src/frontend
        run: npm run lint
      - name: Build
        working-directory: ./src/frontend
        run: npm run build -- --no-lint

  server:
    needs: changes
    if: ${{ (github.event.action != 'closed' || github.event.pull_request.merged) && needs.changes.outputs.server == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          check-latest: true
      - name: Install dependencies
        working-directory: ./src/server
        run: npm ci
      - name: Check Format
        working-directory: ./src/server
        run: npm run format:check
      - name: Build
        working-directory: ./src/server
        run: npm run build
